### ISSUE TITLE
Vb6-Code repository: Exe files infected with malware

### ISSUE THREAD

**Issue by robertjb20** [tannerhelland/vb6-code#1]
All your executeables in this repository are infected with malware. Please remove them or upload virus-free versions. As soon as I extract the .ZIP file or clone this repository, the malware immediately and rapidly tries to infect my computer. Please let me know when you have corrected this problem. Thank you.

**Comment by tannerhelland** [comment]
Hi @robertjb20.  There is no malware in this repository.  I have written about this problem before at length (this article is from one of my most prominent VB6 projects):

https://photodemon.org/2015/04/06/photodemon-and-virustotal-com.html

Unfortunately, because I have shared open-source VB6 code for many years, aspects of my code samples are sometimes used by bad guys as well as good guys.  There's nothing I can do about this - open-source code is, by definition, open to anyone.

The downside is that this sometimes leads virus scanners to incorrectly flag my original sample .exe files as malicious, when you can obviously compile them yourself and see that they are fine.  

I have submitted one of the incorrectly flagged files to Microsoft, but as the above article notes, I no longer waste my time submitting these files to virus scanner companies.  They change their heuristics constantly, and I'm sure the current batch of false-positives for this repo will fade away as quickly as it arose.

GitHub allows you to browse the source code without downloading anything, so if you remain worried, you can also copy out whatever code you want and paste it into a VB6 window yourself.  I feel compelled to provide compiled binaries, however, because many of the developers interested in my code don't use VB6 at all, and can't build the sample projects themselves.

**Comment by tannerhelland** [comment]
Microsoft's security team finished reviewing the problem file.  Here's a screenshot of the analysis they just sent me:

![image](https://user-images.githubusercontent.com/1930029/105388390-d41f9a00-5bd3-11eb-9b1f-65a421b3e430.png)

False-positive, what a surprise!  🙄 

Since many other virus scanners base their work off Microsoft's, I expect this false-positive removal to spread to other software in the coming days.

**Comment by robertjb20** [comment]
Unfortunately, each time I attempt to download your exe files, they actively try to infect my computer, create registry entries without being executed, and each time I try to launch other programs not related to your programs, my anti-virus software blocks aggressive attempts to infect my computer. After I delete your exe files, remove the registry entries from my computer and run a thorough virus scan of my computer, everything is fine. No more attempts to infect my computer.


In all deference to Microsoft, your exe files are infected. I suggest you try to download the files yourself and see the problem in action.


Robert





------------------&nbsp;Original&nbsp;------------------

**Comment by tannerhelland** [comment]
> I suggest you try to download the files yourself and see the problem in action.

What do you think was the first thing I did before I replied to this message?  

I downloaded a fresh copy of the repo from GitHub, used VirusTotal to see which .exe was being flagged, then submitted the .exe to Microsoft (where it was swiftly confirmed as fine, as shown above).

Literally anyone can compile any of the sample projects themselves if they're worried.  If you don't know how to do this, I'm not sure this repo will be of any use to you.

> each time I attempt to download your exe files, they actively try to infect my computer, create registry entries without being executed

I don't even know what to say to this.  If your PC has the magical power to execute freshly downloaded programs without you being involved, you have far bigger problems than anything I could help.

> In all deference to Microsoft, your exe files are infected. 

If you don't believe Microsoft's analysis, you're obviously not going to believe mine.  I'm out.
